version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  producer:
    build: 
      context: ./producer
    depends_on:
      - rabbitmq

  consumer:
    build:
      context: ./consumer
    ports:
      - "80:80"
    depends_on:
      - rabbitmq